# https://github.com/rust-lang/rustfmt/blob/master/Configurations.md
# https://rust-lang.github.io/rustfmt

max_width = 100
use_small_heuristics = "Max"

fn_params_layout = "Compressed"
format_code_in_doc_comments = true
format_macro_matchers = true
group_imports = "StdExternalCrate"
imports_granularity = "Module"
reorder_impl_items = true
# single_line_if_else_max_width = 100
# single_line_let_else_max_width = 100
struct_lit_width = 20
unstable_features = true
use_field_init_shorthand = true
wrap_comments = true
# comment_width = 80
