/*
 Generated by typeshare 1.13.2
*/

/** Create offer request. */
export interface CreateOfferRequest {
	/** Credential issuer identifier (URL). */
	credential_issuer: string;
	/** Issuer's identifier of the intended holder of the credential. */
	subject_id: string;
	/** The identifier of the type of credential to be issued. */
	credential_configuration_id: string;
	/** Type of authorization grant to include in the offer. */
	grant_type: string;
	/**
	 * Whether or not a PIN is required to validate requester of the credential
	 * offer is the person accepting the credential.
	 */
	tx_code_required: boolean;
}

/** Create offer response. */
export interface CreateOfferResponse {
	/** QR code for the credential offer */
	qr_code: string;
	/** PIN code required to accept the credential offer. */
	tx_code?: string;
}

/** Error response. */
export interface ErrorResponse {
	message: string;
}

