name: ci

on:
  push:
    paths:
      - '**/src/**'
      - '**/tests/**'
      - 'Cargo.toml'
      - 'Cargo.lock'
  pull_request:
    paths:
      - '**/src/**'
      - '**/tests/**'
      - 'Cargo.toml'
      - 'Cargo.lock'
  
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  RUSTFLAGS: "-D warnings"
  RUST_BACKTRACE: short
  NEXTEST_PROFILE: ci

jobs:
  test:
    name: Test suite
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
      - uses: taiki-e/install-action@nextest
      - run: |
          sudo apt-get update
      
      - run: cargo nextest run

  test-doc:
    name: Test docs
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
      - run: |
          sudo apt-get update

      - run: cargo test --doc

  # doc:
  #   name: Documentation
  #   runs-on: ubuntu-latest
  #   timeout-minutes: 45
  #   env:
  #     RUSTDOCFLAGS: -Dwarnings
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: dtolnay/rust-toolchain@nightly
  #     - uses: dtolnay/install@cargo-docs-rs
  #     - run: cargo docs-rs -p vercre
  #     - run: cargo docs-rs -p vercre_issuer
  #     - run: cargo docs-rs -p core_utils

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/install@cargo-outdated
      - run: |
          sudo apt-get update

      - run: cargo clippy
